### ISSUE TITLE
Traits with keyword arguments does not work

### ISSUE THREAD

**Issue by davibarreira** [jolin-io/WhereTraits.jl#15]
First of all. Great package! The dispatch in Julia is truly great, and this extension makes it even better.  I was playing around with the package and I realize that it didn't seem to work with keyword arguments, e.g:
```julia
@traits bestprice(b; units) where {units == "cm"} = b
```
Returns the error
```
LoadError: MethodError: Cannot `convert` an object of type Symbol to an object of type Expr
Closest candidates are:
  convert(::Type{Expr}, ::ExprParsers.ExprParsed) at ~/.julia/packages/ExprParsers/snVTb/src/ExprParsers.jl:135
  convert(::Type{T}, ::T) where T at /opt/julia-1.7.1/share/julia/base/essentials.jl:218
  Expr(::Any...) at /opt/julia-1.7.1/share/julia/base/boot.jl:263
in expression starting at In[107]:3
```

The very same code works if I do `bestprice(b, units)`. Is this behavior intended? Is there a way around it?

**Comment by schlichtanders** [comment]
Hi @davibarreira I am back on WhereTraits.

yes, keywordarguments are not supported at the moment.
I updated the documentation because of a new release and have included a limitation node about keyword arguments
