### ISSUE TITLE
Submit to general package registry?

### ISSUE THREAD

**Issue by fingolfin** [jolin-io/WhereTraits.jl#8]
It would be nice if this package was available via the general package registry, to make it easy to use from packages.

**Comment by schlichtanders** [comment]
yes I 100% agree,
as this package is part a full chain of packages and I still have one other package which is not ready to go to General, I was hesitating. 
I hope I find time the next weeks to fix this. Thanks for pushing!

**Comment by fingolfin** [comment]
Thank you!

I have some questions on this package, what is a good venue to ask them? For example, i wonder how well this works with multiple traits of a single argument / traits on multiple arguments? Some experiments seem promising, but all examples in the manual are trivial and don't cover this (or I missed them)

Also I read in the documentation "... And all this works with arbitrary many where expressions ..." but no example, so I am not sure what was meant?

I guess overall my question is "can we please have some more and bigger and complex examples?" ;-).

**Comment by fingolfin** [comment]
In the meantime I'll try to experiment and come up with some examples myself, but I thought you might be able to instantly tell whether multiple traits will work efficiently or not.

**Comment by schlichtanders** [comment]
Hi @fingolfin I now released a new feature to handle complex traits disambiguation.
This includes also a little more complex example now.

I also opened another new ticket for adding more complex examples https://github.com/jolin-io/WhereTraits.jl/issues/17 

closing this as WhereTraits is released to General
